services:
  - type: web
    name: backend-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    region: oregon
