name: Déploiement BudgSmart

on:
  push:
    branches:
      - main

permissions:
  contents: write  # nécessaire pour push sur gh-pages

jobs:
  build-frontend:
    name: Build Frontend dans Docker
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build dans un conteneur Node avec VITE_API_URL
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          docker run --rm \
            -e VITE_API_URL \
            -v ${{ github.workspace }}:/app \
            -w /app/frontend \
            node:20 \
            sh -c "npm install && npm run build"

      - name: Upload du dossier dist/ comme artefact
        uses: actions/upload-artifact@v4
        with:
          name: dist-frontend
          path: frontend/dist

  deploy-frontend:
    name: Déploiement sur GitHub Pages
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout du code (nécessaire pour peaceiris)
        uses: actions/checkout@v4

      - name: Télécharger le build
        uses: actions/download-artifact@v4
        with:
          name: dist-frontend
          path: dist

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
  deploy-backend:
    name: Déploiement Backend et Base de Données
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Installation des dépendances backend
      run: |
        cd backend
        npm ci

    - name: Génération du client Prisma
      run: |
        cd backend
        npm run db:generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Déploiement des migrations de base de données
      run: |
        cd backend
        echo "🗄️ Déploiement des migrations..."
        npm run db:migrate:deploy
        echo "✅ Migrations déployées avec succès"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - name: Test de connexion à la base de données
      run: |
        cd backend
        echo "🔍 Test de connexion à la base de données..."
        npm run db:check
        echo "✅ Base de données opérationnelle"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Déclenchement du déploiement Render
      run: curl "$RENDER_DEPLOY_HOOK_URL"
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
